import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";
import { AmbientPosters } from "@/components/ambient-posters";
import { Header } from "@/components/header";

const departureMono = localFont({
  src: "./fonts/DepartureMono-Regular.woff",
  variable: "--font-departure-mono",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${departureMono.className} antialiased`}>
        <div className="bg-blobs" />
        <AmbientPosters />
        <Header />
        {children}
      </body>
    </html>
  );
}
